// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColumnInfo 列信息
 */
export class ColumnInfo {
    "name": string;
    "type": string;
    "nullable": boolean;
    "defaultValue": string | null;
    "isPrimary": boolean;
    "isAutoIncrement": boolean;
    "comment": string;
    "maxLength": number | null;
    "characterSet": string;
    "collation": string;
    "extra": string;
    "foreignKey": string;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = null;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("isAutoIncrement" in $$source)) {
            this["isAutoIncrement"] = false;
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("maxLength" in $$source)) {
            this["maxLength"] = null;
        }
        if (!("characterSet" in $$source)) {
            this["characterSet"] = "";
        }
        if (!("collation" in $$source)) {
            this["collation"] = "";
        }
        if (!("extra" in $$source)) {
            this["extra"] = "";
        }
        if (!("foreignKey" in $$source)) {
            this["foreignKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

/**
 * ColumnMeta 列元数据
 */
export class ColumnMeta {
    "name": string;
    "type": string;
    "nullable": boolean;

    /** Creates a new ColumnMeta instance. */
    constructor($$source: Partial<ColumnMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnMeta($$parsedSource as Partial<ColumnMeta>);
    }
}

/**
 * ConnectionConfig 连接配置
 */
export class ConnectionConfig {
    "id": string;
    "name": string;
    "type": string;
    "host": string;
    "port": number;
    "user": string;
    "password": string;
    "database": string;
    "sslMode": string;
    "color": string;
    "group": string;

    /**
     * 环境标签：local/test/production
     */
    "tag": string;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

/**
 * DatabaseInfo 数据库信息
 */
export class DatabaseInfo {
    "name": string;
    "tableCount": number;
    "size": number;

    /** Creates a new DatabaseInfo instance. */
    constructor($$source: Partial<DatabaseInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("tableCount" in $$source)) {
            this["tableCount"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseInfo($$parsedSource as Partial<DatabaseInfo>);
    }
}

/**
 * Filter 筛选条件
 */
export class Filter {
    "column": string;
    "operator": string;
    "value": string;

    /** Creates a new Filter instance. */
    constructor($$source: Partial<Filter> = {}) {
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Filter instance from a string or object.
     */
    static createFrom($$source: any = {}): Filter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Filter($$parsedSource as Partial<Filter>);
    }
}

/**
 * IndexInfo 索引信息
 */
export class IndexInfo {
    "name": string;
    "columns": string[];
    "isUnique": boolean;
    "isPrimary": boolean;
    "type": string;
    "comment": string;

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("isUnique" in $$source)) {
            this["isUnique"] = false;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

/**
 * QueryResult 查询结果
 */
export class QueryResult {
    "columns": ColumnMeta[];
    "rows": { [_ in string]?: any }[];
    "total": number;
    "duration": number;
    "error"?: string;

    /**
     * 标记是否被自动追加了 LIMIT
     */
    "autoLimited"?: boolean;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * Sort 排序条件
 */
export class Sort {
    "column": string;
    "direction": string;

    /** Creates a new Sort instance. */
    constructor($$source: Partial<Sort> = {}) {
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sort instance from a string or object.
     */
    static createFrom($$source: any = {}): Sort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sort($$parsedSource as Partial<Sort>);
    }
}

/**
 * StructureColumnEdit 结构编辑：列工作态（与前端 Structure 视图对齐，JSON 由 Wails 绑定）
 */
export class StructureColumnEdit {
    "uid": string;

    /**
     * "", "new", "deleted", "modified"
     */
    "status": string;
    "name": string;
    "type": string;
    "nullable": boolean;
    "defaultValue": string | null;
    "comment": string;

    /** Creates a new StructureColumnEdit instance. */
    constructor($$source: Partial<StructureColumnEdit> = {}) {
        if (!("uid" in $$source)) {
            this["uid"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = null;
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StructureColumnEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): StructureColumnEdit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StructureColumnEdit($$parsedSource as Partial<StructureColumnEdit>);
    }
}

/**
 * StructureIndexEdit 结构编辑：索引工作态
 */
export class StructureIndexEdit {
    "uid": string;
    "status": string;
    "name": string;
    "type": string;
    "isUnique": boolean;
    "isPrimary": boolean;
    "columns": string[];

    /** Creates a new StructureIndexEdit instance. */
    constructor($$source: Partial<StructureIndexEdit> = {}) {
        if (!("uid" in $$source)) {
            this["uid"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("isUnique" in $$source)) {
            this["isUnique"] = false;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StructureIndexEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): StructureIndexEdit {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField6_0($$parsedSource["columns"]);
        }
        return new StructureIndexEdit($$parsedSource as Partial<StructureIndexEdit>);
    }
}

/**
 * TableInfo 表信息
 */
export class TableInfo {
    "name": string;
    "type": string;
    "rowCount": number;
    "size": number;
    "comment": string;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

/**
 * TableStats 表统计信息
 */
export class TableStats {
    "rowCount": number;
    "dataSize": number;
    "indexSize": number;
    "totalSize": number;
    "createTime": string;
    "updateTime": string;
    "engine": string;
    "collation": string;

    /** Creates a new TableStats instance. */
    constructor($$source: Partial<TableStats> = {}) {
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("dataSize" in $$source)) {
            this["dataSize"] = 0;
        }
        if (!("indexSize" in $$source)) {
            this["indexSize"] = 0;
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = "";
        }
        if (!("engine" in $$source)) {
            this["engine"] = "";
        }
        if (!("collation" in $$source)) {
            this["collation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableStats instance from a string or object.
     */
    static createFrom($$source: any = {}): TableStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableStats($$parsedSource as Partial<TableStats>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ColumnMeta.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
