// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocService 文档管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetTableDoc 获取表文档
 */
export function GetTableDoc(connID: string, dbName: string, tableName: string): $CancellablePromise<string> {
    return $Call.ByID(2978867852, connID, dbName, tableName);
}

/**
 * SaveTableDoc 保存表文档
 */
export function SaveTableDoc(connID: string, dbName: string, tableName: string, markdown: string): $CancellablePromise<void> {
    return $Call.ByID(355080489, connID, dbName, tableName, markdown);
}
