// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService 查询历史服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../internal/storage/models.js";

/**
 * AddHistory 添加历史记录
 */
export function AddHistory(connID: string, database: string, sql: string, duration: number, rowCount: number, queryError: string): $CancellablePromise<void> {
    return $Call.ByID(1084229525, connID, database, sql, duration, rowCount, queryError);
}

/**
 * GetFavorites 获取收藏查询
 */
export function GetFavorites(): $CancellablePromise<storage$0.QueryHistoryItem[]> {
    return $Call.ByID(2045058385).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetHistory 获取历史记录
 */
export function GetHistory(limit: number): $CancellablePromise<storage$0.QueryHistoryItem[]> {
    return $Call.ByID(2333786820, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ToggleFavorite 切换收藏
 */
export function ToggleFavorite(id: string): $CancellablePromise<void> {
    return $Call.ByID(922831224, id);
}

// Private type creation functions
const $$createType0 = storage$0.QueryHistoryItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
