// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemaIndexService 对前端暴露 schema 索引状态与刷新能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemaindex$0 from "../internal/schemaindex/models.js";

export function GetSchemaIndexStatus(connID: string, dbName: string): $CancellablePromise<schemaindex$0.Status> {
    return $Call.ByID(2387367594, connID, dbName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RefreshSchemaIndex(connID: string, dbName: string): $CancellablePromise<schemaindex$0.Status> {
    return $Call.ByID(739629465, connID, dbName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WarmSchemaIndex 在后台预热当前库 schema 索引。
 */
export function WarmSchemaIndex(connID: string, dbName: string): $CancellablePromise<void> {
    return $Call.ByID(974057885, connID, dbName);
}

// Private type creation functions
const $$createType0 = schemaindex$0.Status.createFrom;
