// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAIConfig 获取 AI 配置
 */
export function GetAIConfig(): $CancellablePromise<$models.AIConfig | null> {
    return $Call.ByID(3063932341).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLogContent 读取当前日志文件内容（最后 500 行）
 */
export function GetLogContent(): $CancellablePromise<string> {
    return $Call.ByID(567158702);
}

/**
 * GetLogPath 获取日志文件路径
 */
export function GetLogPath(): $CancellablePromise<string> {
    return $Call.ByID(3636110098);
}

/**
 * GetPageSize 获取分页大小设置
 */
export function GetPageSize(): $CancellablePromise<number> {
    return $Call.ByID(2825410847);
}

/**
 * SaveAIConfig 保存 AI 配置到后端存储
 */
export function SaveAIConfig(cfg: $models.AIConfig): $CancellablePromise<void> {
    return $Call.ByID(2673619930, cfg);
}

/**
 * SavePageSize 保存分页大小设置
 */
export function SavePageSize(size: number): $CancellablePromise<void> {
    return $Call.ByID(403527196, size);
}

/**
 * TestAI 测试 AI 连接是否可用
 */
export function TestAI(cfg: $models.AIConfig): $CancellablePromise<string> {
    return $Call.ByID(1254914769, cfg);
}

// Private type creation functions
const $$createType0 = $models.AIConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
