// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * QueryHistoryItem 查询历史条目
 */
export class QueryHistoryItem {
    "id": string;
    "connId": string;
    "database": string;
    "sql": string;
    "duration": number;
    "rowCount": number;
    "error"?: string;
    "favorited": boolean;
    "createdAt": string;

    /** Creates a new QueryHistoryItem instance. */
    constructor($$source: Partial<QueryHistoryItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("favorited" in $$source)) {
            this["favorited"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryHistoryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryHistoryItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryHistoryItem($$parsedSource as Partial<QueryHistoryItem>);
    }
}
