// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as updater$0 from "../../../../../tableplus-ai/internal/updater/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "update:error": updater$0.ErrorPayload;
            "update:progress": updater$0.ProgressPayload;
            "update:ready": updater$0.ReadyPayload;
            "update:state": updater$0.StatePayload;
        }
    }
}
