// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ErrorPayload {
    "state": string;
    "version"?: string;
    "error"?: string;
    "prompt"?: boolean;
    "promptKind"?: string;

    /** Creates a new ErrorPayload instance. */
    constructor($$source: Partial<ErrorPayload> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ErrorPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorPayload($$parsedSource as Partial<ErrorPayload>);
    }
}

export class ProgressPayload {
    "state": string;
    "version"?: string;
    "downloaded": number;
    "total": number;
    "percentage": number;

    /** Creates a new ProgressPayload instance. */
    constructor($$source: Partial<ProgressPayload> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("percentage" in $$source)) {
            this["percentage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgressPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressPayload($$parsedSource as Partial<ProgressPayload>);
    }
}

export class ReadyPayload {
    "state": string;
    "version"?: string;
    "releaseDate"?: string;
    "releaseNotes"?: string;
    "prompt"?: boolean;
    "promptKind"?: string;
    "releaseUrl"?: string;

    /** Creates a new ReadyPayload instance. */
    constructor($$source: Partial<ReadyPayload> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadyPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadyPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadyPayload($$parsedSource as Partial<ReadyPayload>);
    }
}

export class StatePayload {
    "state": string;
    "version"?: string;
    "releaseDate"?: string;
    "releaseNotes"?: string;
    "downloaded"?: number;
    "total"?: number;
    "percentage"?: number;
    "error"?: string;
    "message"?: string;
    "prompt"?: boolean;
    "promptKind"?: string;
    "releaseUrl"?: string;

    /** Creates a new StatePayload instance. */
    constructor($$source: Partial<StatePayload> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): StatePayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatePayload($$parsedSource as Partial<StatePayload>);
    }
}
