// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService AI 功能服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../internal/ai/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeData 数据洞察分析
 */
export function AnalyzeData(columns: string[], rows: { [_ in string]?: any }[], question: string): $CancellablePromise<string> {
    return $Call.ByID(2293082108, columns, rows, question);
}

/**
 * CancelChatStream 取消指定 requestID 的流式 AI 请求。
 */
export function CancelChatStream(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1463831484, requestID);
}

/**
 * ChatAI 会话式 AI 助手（非流式），支持 ReAct 多轮工具调用
 */
export function ChatAI(connID: string, dbName: string, messages: ai$0.ChatMessage[]): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3108170004, connID, dbName, messages).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ChatAIStream 会话式 AI 助手（流式输出），ReAct 模式：AI 边思考边调工具边分析
 */
export function ChatAIStream(connID: string, dbName: string, messages: ai$0.ChatMessage[], requestID: string, sessionID: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(298149868, connID, dbName, messages, requestID, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DiagnoseError 错误诊断
 */
export function DiagnoseError(sqlStr: string, errorMsg: string): $CancellablePromise<string> {
    return $Call.ByID(2988416766, sqlStr, errorMsg);
}

/**
 * ExecuteToolFromAICall 解析 AI 返回的 FunctionToolCall 并执行对应工具
 * 返回工具执行结果的文本输出，供回填到对话历史的 tool 消息中
 */
export function ExecuteToolFromAICall(call: ai$0.FunctionToolCall, connID: string, dbName: string, userQuestion: string, schema: ai$0.SchemaContext | null): $CancellablePromise<$models.aiToolExecutionResult> {
    return $Call.ByID(1719691387, call, connID, dbName, userQuestion, schema).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExplainSQL SQL 解释
 */
export function ExplainSQL(sqlStr: string): $CancellablePromise<string> {
    return $Call.ByID(1718272065, sqlStr);
}

/**
 * GenerateTableDoc 生成表文档
 */
export function GenerateTableDoc(connID: string, dbName: string, tableName: string): $CancellablePromise<string> {
    return $Call.ByID(1125444441, connID, dbName, tableName);
}

/**
 * ListTools 返回当前 AI 可用工具清单，供前端 @tool 联想使用
 */
export function ListTools(): $CancellablePromise<$models.AIToolDefinition[]> {
    return $Call.ByID(1774563475).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * NaturalLanguageToSQL 自然语言转 SQL
 */
export function NaturalLanguageToSQL(connID: string, dbName: string, prompt: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1591034278, connID, dbName, prompt).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReloadConfig 重新加载 AI 配置
 */
export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(1001666503);
}

/**
 * RunChatAutoExecute 在后端完成自动执行意图的安全校验、执行与失败后的 AI 修复重试，返回合并后的助手展示 Markdown
 */
export function RunChatAutoExecute(connID: string, dbName: string, autoExecute: $models.ChatAutoExecuteDirective, assistantContent: string, conversationMessages: ai$0.ChatMessage[], requestID: string): $CancellablePromise<$models.ChatAutoExecuteResult | null> {
    return $Call.ByID(2413004559, connID, dbName, autoExecute, assistantContent, conversationMessages, requestID).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.aiToolExecutionResult.createFrom;
const $$createType2 = $models.AIToolDefinition.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ChatAutoExecuteResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
