// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService 提供应用内稳定的文本复制能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetText 读取系统剪贴板中的文本，用于复制后的校验。
 */
export function GetText(): $CancellablePromise<string> {
    return $Call.ByID(2825601113);
}

/**
 * SetText 将文本写入系统剪贴板。
 */
export function SetText(text: string): $CancellablePromise<void> {
    return $Call.ByID(1706730701, text);
}
