// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService 连接管理服务，负责连接的增删改查和连接/断开操作
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../internal/database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect 根据 ID 从存储加载配置并建立连接
 */
export function Connect(id: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3258834596, id);
}

/**
 * DeleteConnection 删除连接配置，同时断开对应连接
 */
export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1874489421, id);
}

/**
 * Disconnect 断开指定连接
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2398147800, id);
}

/**
 * ExportConnections 导出所有连接配置为 JSON 备份文件（密码为明文，便于跨设备恢复）
 */
export function ExportConnections(): $CancellablePromise<string> {
    return $Call.ByID(392697933);
}

/**
 * GetConnections 获取所有连接配置
 */
export function GetConnections(): $CancellablePromise<database$0.ConnectionConfig[]> {
    return $Call.ByID(3182703551).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportConnections 从 JSON 备份文件导入连接配置（同 ID 已存在则跳过）
 */
export function ImportConnections(): $CancellablePromise<$models.ImportConnectionsResult> {
    return $Call.ByID(2764278856).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveConnection 保存连接配置到本地存储
 */
export function SaveConnection(cfg: database$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(1331699299, cfg);
}

/**
 * TestConnection 测试连接是否可达
 */
export function TestConnection(cfg: database$0.ConnectionConfig): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2075949562, cfg);
}

// Private type creation functions
const $$createType0 = database$0.ConnectionConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ImportConnectionsResult.createFrom;
