// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIConfig AI 配置
 */
export class AIConfig {
    "baseURL": string;
    "apiKey": string;
    "model": string;
    "systemPrompt": string;
    "maxTokens": number;
    "temperature": number;
    "headers"?: { [_ in string]?: string };

    /** Creates a new AIConfig instance. */
    constructor($$source: Partial<AIConfig> = {}) {
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConfig {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new AIConfig($$parsedSource as Partial<AIConfig>);
    }
}

/**
 * AIToolDefinition 定义 AI 可调用工具（可扩展）
 */
export class AIToolDefinition {
    "name": string;
    "description": string;
    "readOnly": boolean;

    /** Creates a new AIToolDefinition instance. */
    constructor($$source: Partial<AIToolDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIToolDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): AIToolDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIToolDefinition($$parsedSource as Partial<AIToolDefinition>);
    }
}

export class AppInfo {
    "name": string;
    "company": string;
    "version": string;
    "commit": string;
    "buildDate": string;
    "repository": string;
    "releaseUrl": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("buildDate" in $$source)) {
            this["buildDate"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * ChatAutoExecuteDirective 保留兼容历史结构，当前主会话链路已不再使用自动执行。
 */
export class ChatAutoExecuteDirective {
    "enabled": boolean;
    "mode"?: string;
    "reason"?: string;

    /** Creates a new ChatAutoExecuteDirective instance. */
    constructor($$source: Partial<ChatAutoExecuteDirective> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatAutoExecuteDirective instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatAutoExecuteDirective {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatAutoExecuteDirective($$parsedSource as Partial<ChatAutoExecuteDirective>);
    }
}

/**
 * ChatAutoExecuteResult 自动执行编排结果（供 Wails 绑定与前端消费，字段名保持稳定）
 */
export class ChatAutoExecuteResult {
    "mergedContent": string;
    "ran": boolean;
    "skipReason"?: string;
    "skippedUnsafe"?: boolean;
    "reasonCode"?: string;
    "verb"?: string;

    /** Creates a new ChatAutoExecuteResult instance. */
    constructor($$source: Partial<ChatAutoExecuteResult> = {}) {
        if (!("mergedContent" in $$source)) {
            this["mergedContent"] = "";
        }
        if (!("ran" in $$source)) {
            this["ran"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatAutoExecuteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatAutoExecuteResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatAutoExecuteResult($$parsedSource as Partial<ChatAutoExecuteResult>);
    }
}

/**
 * BatchUpdateRow 批量事务更新（多行修改一次提交）
 */
export class RowUpdate {
    "primaryKey": { [_ in string]?: any };
    "changes": { [_ in string]?: any };

    /** Creates a new RowUpdate instance. */
    constructor($$source: Partial<RowUpdate> = {}) {
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = {};
        }
        if (!("changes" in $$source)) {
            this["changes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): RowUpdate {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKey" in $$parsedSource) {
            $$parsedSource["primaryKey"] = $$createField0_0($$parsedSource["primaryKey"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField1_0($$parsedSource["changes"]);
        }
        return new RowUpdate($$parsedSource as Partial<RowUpdate>);
    }
}

export class aiToolExecutionResult {
    "ToolName": string;
    "ToolCallID": string;
    "ToolSQL": string;
    "ToolOutput": string;
    "DurationMs": number;
    "Err": any;

    /** Creates a new aiToolExecutionResult instance. */
    constructor($$source: Partial<aiToolExecutionResult> = {}) {
        if (!("ToolName" in $$source)) {
            this["ToolName"] = "";
        }
        if (!("ToolCallID" in $$source)) {
            this["ToolCallID"] = "";
        }
        if (!("ToolSQL" in $$source)) {
            this["ToolSQL"] = "";
        }
        if (!("ToolOutput" in $$source)) {
            this["ToolOutput"] = "";
        }
        if (!("DurationMs" in $$source)) {
            this["DurationMs"] = 0;
        }
        if (!("Err" in $$source)) {
            this["Err"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new aiToolExecutionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): aiToolExecutionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new aiToolExecutionResult($$parsedSource as Partial<aiToolExecutionResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
