// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * AIConfig AI 配置
 */
export class AIConfig {
    "baseURL": string;
    "apiKey": string;
    "model": string;
    "systemPrompt": string;
    "maxTokens": number;
    "temperature": number;
    "headers"?: { [_ in string]?: string };

    /** Creates a new AIConfig instance. */
    constructor($$source: Partial<AIConfig> = {}) {
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConfig {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new AIConfig($$parsedSource as Partial<AIConfig>);
    }
}

/**
 * AISessionMessageView 会话消息视图（含结构化工具结果）。
 */
export class AISessionMessageView {
    "id": string;
    "role": string;
    "content": string;
    "toolName"?: string;
    "toolSql"?: string;
    "toolResult"?: { [_ in string]?: any };
    "createdAt": time$0.Time;

    /** Creates a new AISessionMessageView instance. */
    constructor($$source: Partial<AISessionMessageView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISessionMessageView instance from a string or object.
     */
    static createFrom($$source: any = {}): AISessionMessageView {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolResult" in $$parsedSource) {
            $$parsedSource["toolResult"] = $$createField5_0($$parsedSource["toolResult"]);
        }
        return new AISessionMessageView($$parsedSource as Partial<AISessionMessageView>);
    }
}

/**
 * AISessionView 对前端暴露的会话视图（与 storage.AISession 一致，字段名稳定）。
 */
export class AISessionView {
    "id": string;
    "title": string;
    "connectionId"?: string;
    "database"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "messageCount": number;

    /** Creates a new AISessionView instance. */
    constructor($$source: Partial<AISessionView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("messageCount" in $$source)) {
            this["messageCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISessionView instance from a string or object.
     */
    static createFrom($$source: any = {}): AISessionView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AISessionView($$parsedSource as Partial<AISessionView>);
    }
}

/**
 * AIToolDefinition 定义 AI 可调用工具（可扩展）
 */
export class AIToolDefinition {
    "name": string;
    "description": string;
    "readOnly": boolean;
    "resultKind"?: string;

    /** Creates a new AIToolDefinition instance. */
    constructor($$source: Partial<AIToolDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIToolDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): AIToolDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIToolDefinition($$parsedSource as Partial<AIToolDefinition>);
    }
}

export class AnalyticsConfig {
    "enabled": boolean;
    "installationId": string;
    "appVersion": string;
    "os": string;
    "arch": string;

    /** Creates a new AnalyticsConfig instance. */
    constructor($$source: Partial<AnalyticsConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("installationId" in $$source)) {
            this["installationId"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyticsConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyticsConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyticsConfig($$parsedSource as Partial<AnalyticsConfig>);
    }
}

export class AppInfo {
    "name": string;
    "company": string;
    "version": string;
    "commit": string;
    "buildDate": string;
    "repository": string;
    "releaseUrl": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("company" in $$source)) {
            this["company"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("buildDate" in $$source)) {
            this["buildDate"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

/**
 * ImportConnectionsResult 导入连接配置结果
 */
export class ImportConnectionsResult {
    "imported": number;
    "skipped": number;

    /** Creates a new ImportConnectionsResult instance. */
    constructor($$source: Partial<ImportConnectionsResult> = {}) {
        if (!("imported" in $$source)) {
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportConnectionsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportConnectionsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportConnectionsResult($$parsedSource as Partial<ImportConnectionsResult>);
    }
}

/**
 * BatchUpdateRow 批量事务更新（多行修改一次提交）
 */
export class RowUpdate {
    "primaryKey": { [_ in string]?: any };
    "changes": { [_ in string]?: any };

    /** Creates a new RowUpdate instance. */
    constructor($$source: Partial<RowUpdate> = {}) {
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = {};
        }
        if (!("changes" in $$source)) {
            this["changes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): RowUpdate {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryKey" in $$parsedSource) {
            $$parsedSource["primaryKey"] = $$createField0_0($$parsedSource["primaryKey"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField1_0($$parsedSource["changes"]);
        }
        return new RowUpdate($$parsedSource as Partial<RowUpdate>);
    }
}

/**
 * 注意：aiToolExecutionResult 仅为兼容旧 execToolXX 与旧测试保留；
 * 新 Agent 链路统一使用 *agent.ToolResult（见 toolResultFromExec / 注册表）。
 */
export class aiToolExecutionResult {
    "ToolName": string;
    "ToolCallID": string;
    "ToolSQL": string;
    "ToolOutput": string;
    "DurationMs": number;
    "Err": any;

    /**
     * 结构化字段：供新事件协议使用（rows 结果 / 截断标记 / 附加元数据）
     */
    "columns"?: string[];
    "rows"?: { [_ in string]?: any }[];
    "truncated"?: boolean;
    "data"?: { [_ in string]?: any };

    /** Creates a new aiToolExecutionResult instance. */
    constructor($$source: Partial<aiToolExecutionResult> = {}) {
        if (!("ToolName" in $$source)) {
            this["ToolName"] = "";
        }
        if (!("ToolCallID" in $$source)) {
            this["ToolCallID"] = "";
        }
        if (!("ToolSQL" in $$source)) {
            this["ToolSQL"] = "";
        }
        if (!("ToolOutput" in $$source)) {
            this["ToolOutput"] = "";
        }
        if (!("DurationMs" in $$source)) {
            this["DurationMs"] = 0;
        }
        if (!("Err" in $$source)) {
            this["Err"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new aiToolExecutionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): aiToolExecutionResult {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField6_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField7_0($$parsedSource["rows"]);
        }
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField9_0($$parsedSource["data"]);
        }
        return new aiToolExecutionResult($$parsedSource as Partial<aiToolExecutionResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType1);
