// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../internal/updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(1723753862);
}

/**
 * GetAIConfig 获取 AI 配置
 */
export function GetAIConfig(): $CancellablePromise<$models.AIConfig | null> {
    return $Call.ByID(3249539797).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(3939318168).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetLogContent 读取当前日志文件内容（最后 500 行）
 */
export function GetLogContent(): $CancellablePromise<string> {
    return $Call.ByID(1861779598);
}

/**
 * GetLogPath 获取日志文件路径
 */
export function GetLogPath(): $CancellablePromise<string> {
    return $Call.ByID(3213057650);
}

/**
 * GetPageSize 获取分页大小设置
 */
export function GetPageSize(): $CancellablePromise<number> {
    return $Call.ByID(3040537215);
}

export function GetUpdateStatus(): $CancellablePromise<updater$0.StatePayload> {
    return $Call.ByID(4293687494).then(($result: any) => {
        return $$createType3($result);
    });
}

export function InstallReadyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1172108504);
}

/**
 * SaveAIConfig 保存 AI 配置到后端存储
 */
export function SaveAIConfig(cfg: $models.AIConfig): $CancellablePromise<void> {
    return $Call.ByID(2673100538, cfg);
}

/**
 * SavePageSize 保存分页大小设置
 */
export function SavePageSize(size: number): $CancellablePromise<void> {
    return $Call.ByID(2944019964, size);
}

/**
 * TestAI 测试 AI 连接是否可用
 */
export function TestAI(cfg: $models.AIConfig): $CancellablePromise<string> {
    return $Call.ByID(25254705, cfg);
}

// Private type creation functions
const $$createType0 = $models.AIConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AppInfo.createFrom;
const $$createType3 = updater$0.StatePayload.createFrom;
