// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChatMessage 聊天消息结构
 */
export class ChatMessage {
    "role": string;
    "content": string;

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

/**
 * ColumnSchema 列结构
 */
export class ColumnSchema {
    "Name": string;
    "Type": string;
    "Nullable": boolean;
    "Comment": string;

    /**
     * 是否为主键
     */
    "IsPrimary": boolean;

    /**
     * 默认值
     */
    "DefaultValue": string;

    /**
     * 外键引用（如 "other_table.id"）
     */
    "ForeignKey": string;

    /** Creates a new ColumnSchema instance. */
    constructor($$source: Partial<ColumnSchema> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Nullable" in $$source)) {
            this["Nullable"] = false;
        }
        if (!("Comment" in $$source)) {
            this["Comment"] = "";
        }
        if (!("IsPrimary" in $$source)) {
            this["IsPrimary"] = false;
        }
        if (!("DefaultValue" in $$source)) {
            this["DefaultValue"] = "";
        }
        if (!("ForeignKey" in $$source)) {
            this["ForeignKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnSchema {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnSchema($$parsedSource as Partial<ColumnSchema>);
    }
}

/**
 * FunctionToolCall 表示模型返回的一次函数调用
 */
export class FunctionToolCall {
    "ID": string;
    "Name": string;
    "Arguments": string;

    /** Creates a new FunctionToolCall instance. */
    constructor($$source: Partial<FunctionToolCall> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Arguments" in $$source)) {
            this["Arguments"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FunctionToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): FunctionToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FunctionToolCall($$parsedSource as Partial<FunctionToolCall>);
    }
}

/**
 * SchemaContext 表结构上下文
 */
export class SchemaContext {
    "DatabaseType": string;
    "DatabaseName": string;

    /**
     * 数据库服务器版本（如 "8.0.11-TiDB-v7.5.3"）
     */
    "DatabaseVersion": string;
    "Tables": TableSchema[];

    /** Creates a new SchemaContext instance. */
    constructor($$source: Partial<SchemaContext> = {}) {
        if (!("DatabaseType" in $$source)) {
            this["DatabaseType"] = "";
        }
        if (!("DatabaseName" in $$source)) {
            this["DatabaseName"] = "";
        }
        if (!("DatabaseVersion" in $$source)) {
            this["DatabaseVersion"] = "";
        }
        if (!("Tables" in $$source)) {
            this["Tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaContext instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaContext {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tables" in $$parsedSource) {
            $$parsedSource["Tables"] = $$createField3_0($$parsedSource["Tables"]);
        }
        return new SchemaContext($$parsedSource as Partial<SchemaContext>);
    }
}

/**
 * TableSchema 表结构
 */
export class TableSchema {
    "Name": string;

    /**
     * 表注释
     */
    "Comment": string;
    "Columns": ColumnSchema[];

    /** Creates a new TableSchema instance. */
    constructor($$source: Partial<TableSchema> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Comment" in $$source)) {
            this["Comment"] = "";
        }
        if (!("Columns" in $$source)) {
            this["Columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): TableSchema {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Columns" in $$parsedSource) {
            $$parsedSource["Columns"] = $$createField2_0($$parsedSource["Columns"]);
        }
        return new TableSchema($$parsedSource as Partial<TableSchema>);
    }
}

// Private type creation functions
const $$createType0 = TableSchema.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ColumnSchema.createFrom;
const $$createType3 = $Create.Array($$createType2);
