// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceMemory = "memory",
    SourcePersisted = "persisted",
    SourceRebuilt = "rebuilt",
};

export class Status {
    "schemaKey"?: string;
    "databaseName"?: string;
    "exists": boolean;
    "refreshing": boolean;
    "dirty": boolean;
    "stale": boolean;
    "lastRefreshedAt"?: string;
    "lastError"?: string;
    "tableCount": number;
    "source"?: Source;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("refreshing" in $$source)) {
            this["refreshing"] = false;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }
        if (!("stale" in $$source)) {
            this["stale"] = false;
        }
        if (!("tableCount" in $$source)) {
            this["tableCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
